/* ============================================================
   Blog posts data — shared across blogs.html & blog-detail.html
============================================================ */
var BLOGS = [
  {
    slug:     'speed-up-wordpress-site',
    tag:      'Performance',
    title:    'How to Speed Up Your WordPress Site in 2024',
    excerpt:  'A slow website kills conversions. Here are the most effective, practical steps to cut your WordPress load time and pass Core Web Vitals.',
    date:     'March 10, 2025',
    readTime: '6 min read',
    img:      'assets/images/services-img.png',
    content: [
      { type: 'p', text: 'Page speed is one of the most overlooked aspects of WordPress development. A site that loads in under 2 seconds converts significantly better than one that takes 4+ seconds — and Google uses it as a direct ranking factor. The good news is that most speed issues come from a small set of common mistakes that are easy to fix.' },
      { type: 'h2', text: '1. Choose the Right Hosting' },
      { type: 'p', text: 'Shared hosting is the number one cause of slow WordPress sites. No amount of optimisation will compensate for a server that\'s overloaded with thousands of other websites. If you\'re serious about performance, move to a managed WordPress host like Kinsta, WP Engine, or SiteGround\'s Business plan. The cost difference is worth it.' },
      { type: 'h2', text: '2. Install a Caching Plugin' },
      { type: 'p', text: 'Caching stores a static copy of your pages so WordPress doesn\'t have to rebuild them from scratch on every visit. WP Rocket is the gold standard — it handles page caching, browser caching, database cleanup, and lazy loading in one plugin. If you\'re on a budget, W3 Total Cache or LiteSpeed Cache are solid free alternatives.' },
      { type: 'h2', text: '3. Optimise Every Image' },
      { type: 'p', text: 'Images are usually the heaviest assets on any page. Before uploading, compress images using Squoosh or TinyPNG. Then use a plugin like Imagify or ShortPixel to automatically compress future uploads. Also convert images to WebP format — it\'s 25–35% smaller than JPEG/PNG at the same visual quality.' },
      { type: 'ul', items: [
        'Use WebP format for all images',
        'Enable lazy loading so off-screen images don\'t block initial render',
        'Set explicit width and height attributes to prevent layout shift (CLS)',
        'Serve images at the correct display size — never larger',
      ]},
      { type: 'h2', text: '4. Minimise Plugin Bloat' },
      { type: 'p', text: 'Every plugin you install adds PHP execution time, database queries, and often extra CSS/JS files. Audit your plugins regularly. Remove anything you don\'t actively use, and replace heavy plugins with lightweight alternatives where possible. Query Monitor is a free plugin that shows you exactly which plugins are slowing down each page.' },
      { type: 'quote', text: 'The fastest plugin is the one you don\'t install.' },
      { type: 'p', text: 'Start with a performance audit using Google PageSpeed Insights or GTmetrix. Fix the issues flagged there in priority order. Most sites can achieve a 90+ performance score with just hosting, caching, and image optimisation sorted.' },
    ],
    tags: ['WordPress', 'Performance', 'Core Web Vitals', 'SEO'],
    related: ['local-seo-small-business', 'woocommerce-vs-shopify'],
  },
  {
    slug:     'woocommerce-vs-shopify',
    tag:      'E-Commerce',
    title:    'WooCommerce vs Shopify: Which is Right for Your Store?',
    excerpt:  'Both platforms can build a great online store — but they suit very different business types. Here\'s how to decide which one is right for you.',
    date:     'February 24, 2025',
    readTime: '7 min read',
    img:      'assets/images/about-img.png',
    content: [
      { type: 'p', text: 'When clients ask me which platform to use for their online store, the answer is never the same. WooCommerce and Shopify are both excellent — but they\'re built for different types of businesses, budgets, and levels of technical comfort. Here\'s a clear breakdown to help you choose.' },
      { type: 'h2', text: 'The Core Difference' },
      { type: 'p', text: 'Shopify is a fully hosted, all-in-one SaaS platform. You pay a monthly subscription and Shopify handles hosting, security, and updates. WooCommerce is a free WordPress plugin that you self-host — meaning more control, but also more responsibility.' },
      { type: 'h2', text: 'When to Choose Shopify' },
      { type: 'ul', items: [
        'You want to launch quickly without touching code',
        'You\'re selling physical products with straightforward shipping',
        'You don\'t want to manage hosting or updates',
        'Your budget allows $29–$299/month in platform fees',
        'You need built-in abandoned cart recovery and multi-currency out of the box',
      ]},
      { type: 'h2', text: 'When to Choose WooCommerce' },
      { type: 'ul', items: [
        'You already have a WordPress site and want to add a store',
        'You need deep customisation of the checkout or product pages',
        'You\'re selling digital downloads, subscriptions, or bookings',
        'You want to avoid per-transaction fees on payment gateways',
        'You need full ownership of your data and no platform lock-in',
      ]},
      { type: 'quote', text: 'Shopify is simpler to run. WooCommerce is more powerful to customise. Your choice should depend on which trade-off matters more to your business.' },
      { type: 'h2', text: 'Cost Comparison' },
      { type: 'p', text: 'Shopify\'s Basic plan starts at $29/month plus transaction fees if you don\'t use Shopify Payments. WooCommerce itself is free, but you\'ll pay for hosting ($10–$30/month), a theme, and premium plugins. For a fully-featured store, both platforms end up costing roughly the same over 12 months — but WooCommerce gives you more for that money.' },
      { type: 'p', text: 'My recommendation: if you\'re a non-technical founder launching your first store, start with Shopify. If you\'re building something bespoke or already on WordPress, WooCommerce is the better long-term investment.' },
    ],
    tags: ['WooCommerce', 'Shopify', 'E-Commerce', 'WordPress'],
    related: ['speed-up-wordpress-site', 'mobile-experience-kills-sales'],
  },
  {
    slug:     'css-tricks-frontend-developers',
    tag:      'Frontend',
    title:    '10 CSS Tricks Every Frontend Developer Should Know',
    excerpt:  'From clamp() for fluid typography to :has() for parent selectors — these modern CSS features will change how you write layouts.',
    date:     'February 8, 2025',
    readTime: '5 min read',
    img:      'assets/images/services-img.png',
    content: [
      { type: 'p', text: 'Modern CSS has evolved dramatically. Many things that required JavaScript or complex hacks a few years ago can now be done with a single line of CSS. Here are ten techniques I use in almost every project.' },
      { type: 'h2', text: '1. clamp() for Fluid Typography' },
      { type: 'p', text: 'Instead of writing media queries for every font size breakpoint, use clamp(). It sets a minimum size, a preferred fluid size, and a maximum — all in one value.' },
      { type: 'code', text: 'font-size: clamp(1rem, 2.5vw, 1.5rem);' },
      { type: 'h2', text: '2. CSS Custom Properties (Variables)' },
      { type: 'p', text: 'Define your colour palette, spacing scale, and transition speeds as CSS variables at the :root level. This makes global theme changes trivial and keeps your CSS DRY.' },
      { type: 'h2', text: '3. aspect-ratio for Consistent Image Boxes' },
      { type: 'p', text: 'Stop using the padding-top hack. The aspect-ratio property lets you define the ratio of any element in a single, readable property.' },
      { type: 'code', text: '.card-img { aspect-ratio: 16 / 9; object-fit: cover; }' },
      { type: 'h2', text: '4. :is() and :where() for Cleaner Selectors' },
      { type: 'p', text: 'Group multiple selectors without repeating yourself. :is() carries the specificity of its most specific argument, while :where() always has zero specificity — useful for resets.' },
      { type: 'h2', text: '5. gap Instead of margin on Flex/Grid' },
      { type: 'p', text: 'Use gap on flex and grid containers instead of adding margin to every child element. It\'s cleaner, doesn\'t affect the outer edges, and works perfectly with wrapping layouts.' },
      { type: 'ul', items: [
        'scroll-behavior: smooth — native smooth scrolling, no JS',
        'position: sticky — sticky headers without scroll listeners',
        'text-wrap: balance — evenly balanced headline line breaks',
        'color-scheme: dark light — automatic dark mode support',
        'container queries — component-level responsive design',
      ]},
      { type: 'quote', text: 'The best CSS is the CSS you don\'t need to write. Let the browser do the heavy lifting.' },
      { type: 'p', text: 'These features are all well-supported in modern browsers. Start using them today and your stylesheets will be cleaner, more maintainable, and far easier to debug.' },
    ],
    tags: ['CSS', 'Frontend', 'Web Design', 'JavaScript'],
    related: ['mobile-experience-kills-sales', 'speed-up-wordpress-site'],
  },
  {
    slug:     'local-seo-small-business',
    tag:      'SEO',
    title:    'How to Set Up Local SEO for a Small Business Website',
    excerpt:  'If your customers are local, your website should show up when they search. Here\'s a step-by-step guide to getting found in local search results.',
    date:     'January 20, 2025',
    readTime: '8 min read',
    img:      'assets/images/about-img.png',
    content: [
      { type: 'p', text: 'Local SEO is one of the highest-ROI marketing activities for small businesses. When someone searches for "plumber near me" or "web designer in Karachi", Google serves results based on proximity, relevance, and authority. Here\'s how to ensure your business appears at the top.' },
      { type: 'h2', text: '1. Claim and Optimise Your Google Business Profile' },
      { type: 'p', text: 'This is the single most important step. Go to business.google.com, claim your listing, and fill out every field. Add your correct NAP (Name, Address, Phone), business hours, website URL, photos, and a detailed description with your primary keywords. Respond to every review — positive and negative.' },
      { type: 'h2', text: '2. NAP Consistency Across the Web' },
      { type: 'p', text: 'Your business name, address, and phone number must be identical everywhere they appear online — your website, Google Business, Yelp, Facebook, industry directories. Even small differences (e.g. "St." vs "Street") confuse Google\'s local algorithm.' },
      { type: 'h2', text: '3. Create Location-Specific Pages' },
      { type: 'p', text: 'If you serve multiple areas, create a dedicated page for each. A cleaning company serving London, Manchester, and Birmingham should have three separate service-area pages — each with unique content, local landmarks, and location-specific keywords.' },
      { type: 'ul', items: [
        'Add LocalBusiness schema markup to your homepage',
        'Embed a Google Map on your contact page',
        'Get listed in local directories (Yell, Thomson Local, etc.)',
        'Earn backlinks from local blogs, news sites, and business associations',
        'Use location keywords naturally in your page titles and headings',
      ]},
      { type: 'quote', text: 'Local SEO is a long game, but the results compound. A business that invests in it consistently for 6 months will dominate its local search results for years.' },
      { type: 'h2', text: '4. Reviews Are Your Local Currency' },
      { type: 'p', text: 'Google heavily weights review quantity and quality for local rankings. Set up an automated system to ask every happy customer for a Google review — a simple follow-up email or WhatsApp message with a direct link to your review form. Aim for at least 20 reviews in your first 3 months.' },
    ],
    tags: ['SEO', 'Local SEO', 'WordPress', 'Google'],
    related: ['speed-up-wordpress-site', 'woocommerce-vs-shopify'],
  },
  {
    slug:     'learndash-vs-lifterlms',
    tag:      'LMS',
    title:    'LearnDash vs LifterLMS: Which LMS Plugin Wins in 2025?',
    excerpt:  'Both are top-tier WordPress LMS plugins — but they have very different strengths. Here\'s which one I recommend and why.',
    date:     'January 5, 2025',
    readTime: '6 min read',
    img:      'assets/images/services-img.png',
    content: [
      { type: 'p', text: 'If you\'re building an online academy on WordPress, you\'ll quickly narrow your options down to two dominant plugins: LearnDash and LifterLMS. I\'ve built live academies with both — here\'s my honest comparison.' },
      { type: 'h2', text: 'LearnDash — Best for Structured Courses' },
      { type: 'p', text: 'LearnDash is the most widely used LMS plugin, powering platforms for universities, corporate training companies, and individual instructors. Its course builder is drag-and-drop, supports quizzes with multiple question types, and has a clean student dashboard. It integrates with WooCommerce and most membership plugins out of the box.' },
      { type: 'ul', items: [
        'Price: from $199/year for a single site',
        'Best for: structured multi-course academies',
        'Strengths: quiz engine, certificates, drip content',
        'Weakness: the UI feels dated compared to newer tools',
      ]},
      { type: 'h2', text: 'LifterLMS — Best for All-in-One Simplicity' },
      { type: 'p', text: 'LifterLMS takes a more all-in-one approach. The core plugin is free and already includes course creation, student progress tracking, and basic certificates. Paid add-ons handle payment gateways, groups, and advanced certificates. For a solo instructor selling a single course, LifterLMS can be launched with minimal upfront cost.' },
      { type: 'ul', items: [
        'Price: free core + paid add-ons from $99/year',
        'Best for: solo instructors and small academies',
        'Strengths: free to start, built-in payment processing',
        'Weakness: add-on costs can add up for larger setups',
      ]},
      { type: 'quote', text: 'LearnDash if you\'re building something serious and scalable. LifterLMS if you want to start fast and keep costs low.' },
      { type: 'h2', text: 'My Recommendation' },
      { type: 'p', text: 'For clients building a full academy with multiple instructors, advanced quizzes, and corporate enrolment flows, I recommend LearnDash. For individuals selling a course or two and wanting to launch quickly, LifterLMS is the better starting point. Either way, both plugins are solid — the difference is in the scale and complexity of what you\'re building.' },
    ],
    tags: ['LMS', 'LearnDash', 'LifterLMS', 'WordPress', 'E-Learning'],
    related: ['speed-up-wordpress-site', 'woocommerce-vs-shopify'],
  },
  {
    slug:     'mobile-experience-kills-sales',
    tag:      'Web Design',
    title:    'Why Your Website\'s Mobile Experience is Killing Your Sales',
    excerpt:  'Over 60% of web traffic is mobile — yet most small business websites still treat mobile as an afterthought. Here\'s what it\'s costing you.',
    date:     'December 18, 2024',
    readTime: '5 min read',
    img:      'assets/images/about-img.png',
    content: [
      { type: 'p', text: 'In 2024, over 60% of all web traffic comes from mobile devices. Yet when I audit small business websites, the most common issue I find is a desktop site that technically "works" on mobile — but barely. Buttons that are too small to tap, text that requires zooming to read, and forms that are impossible to complete without a physical keyboard. This costs businesses real money.' },
      { type: 'h2', text: 'The Numbers Don\'t Lie' },
      { type: 'p', text: 'Google research shows that 53% of mobile users abandon a page that takes longer than 3 seconds to load. And 61% say they\'re unlikely to return to a site they had trouble accessing on mobile. Every broken mobile experience is a lost customer — often permanently.' },
      { type: 'h2', text: 'The Most Common Mobile Mistakes' },
      { type: 'ul', items: [
        'Tap targets smaller than 44×44px — impossible to hit accurately on a phone',
        'Text smaller than 16px — forces users to zoom in to read anything',
        'Horizontal scrolling caused by fixed-width elements',
        'Pop-ups or overlays that cover the entire screen and can\'t be closed',
        'Forms with too many fields that aren\'t optimised for mobile keyboards',
        'Navigation menus that don\'t collapse properly on small screens',
      ]},
      { type: 'h2', text: 'Mobile-First Is Not Optional' },
      { type: 'p', text: 'The correct approach is to design and build mobile layouts first, then scale up to desktop — not the other way around. This forces you to prioritise the most important content and interactions, resulting in a cleaner experience on all screen sizes.' },
      { type: 'quote', text: 'If your website isn\'t effortless on a phone, your competitor\'s is.' },
      { type: 'h2', text: 'Quick Wins to Fix Today' },
      { type: 'p', text: 'Open your site on your own phone right now. Try to navigate, read the content, and complete your main call-to-action without pinching, zooming, or getting frustrated. If you can\'t do it comfortably, your customers can\'t either. Start with font sizes, button sizes, and your contact form — those three fixes alone will have a measurable impact on conversions.' },
    ],
    tags: ['Web Design', 'Mobile', 'UX', 'Responsive'],
    related: ['css-tricks-frontend-developers', 'speed-up-wordpress-site'],
  },
];
