/* ============================================================
   Projects data — shared across work.html & project-detail.html
============================================================ */
var PROJECTS = [
  {
    slug:     'exclusiveprocleaning',
    title:    'exclusiveprocleaning.co.uk',
    category: 'WordPress',
    sub:      'Cleaning Services',
    location: 'United Kingdom',
    year:     '2024',
    url:      'https://exclusiveprocleaning.co.uk',
    stack:    ['WordPress', 'Divi', 'PHP', 'CSS3'],
    overview: 'A professional cleaning services website built for a UK-based company. The site features a clean, modern design with detailed service listings, instant quote forms, and a fully optimised structure for local SEO — helping the business rank higher in London search results.',
    services: ['Custom WordPress Theme', 'Responsive Design', 'Local SEO Setup', 'Lead Generation Forms'],
    img:      'assets/images/services-img.png'
  },
  {
    slug:     'vapehp',
    title:    'vapehp.ca',
    category: 'WooCommerce',
    sub:      'E-Commerce',
    location: 'Canada',
    year:     '2024',
    url:      'https://vapehp.ca',
    stack:    ['WooCommerce', 'WordPress', 'PHP', 'Stripe'],
    overview: 'A full-featured WooCommerce store built for a Canadian vape retailer. The project included custom product pages, age-verification flows, payment gateway integration, and a streamlined checkout experience optimised for conversion.',
    services: ['WooCommerce Development', 'Payment Integration', 'Age Verification', 'Performance Optimisation'],
    img:      'assets/images/services-img.png'
  },
  {
    slug:     'vortexwise',
    title:    'vortexwise.com',
    category: 'WordPress',
    sub:      'Amazon UGC / Marketing',
    location: 'Pakistan',
    year:     '2024',
    url:      'https://vortexwise.com',
    stack:    ['WordPress', 'Elementor', 'PHP', 'CSS3'],
    overview: 'A marketing and Amazon UGC agency website designed to attract brand clients. Built with a bold visual language, clear service breakdowns, and portfolio sections that showcase content creation work for Amazon sellers.',
    services: ['WordPress Development', 'Custom Design', 'Portfolio Integration', 'Contact & CRM Forms'],
    img:      'assets/images/services-img.png'
  },
  {
    slug:     'sherdilcloud',
    title:    'sherdilcloud.com',
    category: 'WordPress',
    sub:      'IT / Cloud Services',
    location: 'Pakistan',
    year:     '2023',
    url:      'https://sherdilcloud.com',
    stack:    ['WordPress', 'Beaver Builder', 'PHP'],
    overview: 'Corporate IT and cloud services website for a Pakistani tech company. Focused on a clean, professional aesthetic with service pages, team profiles, and a client portal entry point. Fully responsive across all devices.',
    services: ['Corporate Website', 'Beaver Builder', 'Service Page Design', 'Responsive Build'],
    img:      'assets/images/services-img.png'
  },
  {
    slug:     'academy-sherdil',
    title:    'academy.sherdil.org',
    category: 'WordPress / LMS',
    sub:      'Online Academy',
    location: 'Pakistan',
    year:     '2023',
    url:      'https://academy.sherdil.org',
    stack:    ['WordPress', 'LearnDash', 'WooCommerce', 'PHP'],
    overview: 'A full Learning Management System built on WordPress with LearnDash. Students can enrol, purchase courses, track progress, and receive certificates. Integrated with WooCommerce for course sales and PayPal for payments.',
    services: ['LMS Development', 'LearnDash Setup', 'WooCommerce Integration', 'Student Dashboard'],
    img:      'assets/images/services-img.png'
  },
  {
    slug:     'diamond-dpc',
    title:    'diamond-dpc.com',
    category: 'WordPress',
    sub:      'Events / Lead Generation',
    location: 'United Kingdom',
    year:     '2023',
    url:      'https://diamond-dpc.com',
    stack:    ['WordPress', 'Divi', 'PHP', 'Mailchimp'],
    overview: 'An events and lead generation site for a UK-based business. Features include event listings, registration forms connected to Mailchimp, a custom Divi layout, and strong calls-to-action designed to maximise lead capture.',
    services: ['WordPress + Divi', 'Event Listings', 'Mailchimp Integration', 'Lead Gen Forms'],
    img:      'assets/images/services-img.png'
  },
  {
    slug:     'genzjewellery',
    title:    'genzjewellery.com',
    category: 'WooCommerce',
    sub:      'E-Commerce (Jewelry)',
    location: 'Pakistan',
    year:     '2023',
    url:      'https://genzjewellery.com',
    stack:    ['WooCommerce', 'WordPress', 'PHP', 'CSS3'],
    overview: 'A luxury jewellery e-commerce store with a sophisticated dark-and-gold aesthetic. Product filtering, wishlist functionality, and an intuitive checkout flow were central to the build. Mobile-first design throughout.',
    services: ['WooCommerce Store', 'Custom Theme', 'Product Filters', 'Wishlist & Cart UX'],
    img:      'assets/images/services-img.png'
  },
  {
    slug:     'pixowallpapers',
    title:    'pixowallpapers.com',
    category: 'WordPress',
    sub:      'Wallpaper Gallery',
    location: 'Pakistan',
    year:     '2023',
    url:      'https://pixowallpapers.com',
    stack:    ['WordPress', 'PHP', 'CSS3', 'jQuery'],
    overview: 'A high-performance wallpaper gallery website with thousands of images. Built with lazy loading, category filters, and one-click downloads. Heavily optimised for speed and Google image search visibility.',
    services: ['WordPress Gallery', 'Lazy Loading', 'Category System', 'Download Functionality'],
    img:      'assets/images/services-img.png'
  },
  {
    slug:     'importedvitamins',
    title:    'importedvitamins.com',
    category: 'WooCommerce',
    sub:      'E-Commerce (Health)',
    location: 'Pakistan',
    year:     '2023',
    url:      'https://importedvitamins.com',
    stack:    ['WooCommerce', 'WordPress', 'PHP', 'CSS3'],
    overview: 'A health supplements e-commerce store selling imported vitamins across Pakistan. Built with product variant support, bulk order discounts, and a clean UI that builds trust in the health-conscious buyer.',
    services: ['WooCommerce Development', 'Product Variants', 'Bulk Discount Rules', 'Checkout Optimisation'],
    img:      'assets/images/services-img.png'
  },
  {
    slug:     'thedesignersboutique',
    title:    'thedesignersboutique.co.uk',
    category: 'Divi / WordPress',
    sub:      'Fashion & Retail',
    location: 'United Kingdom',
    year:     '2022',
    url:      'https://thedesignersboutique.co.uk',
    stack:    ['WordPress', 'Divi', 'WooCommerce', 'PHP'],
    overview: 'A fashion retail website for a UK boutique selling designer clothing. Combines a sleek WooCommerce store with editorial-style product showcases and a curated brand aesthetic that resonates with fashion-conscious shoppers.',
    services: ['Divi Theme', 'WooCommerce Store', 'Editorial Design', 'Fashion UX'],
    img:      'assets/images/services-img.png'
  },
  {
    slug:     'techspark',
    title:    'techspark.solutions',
    category: 'Beaver Builder',
    sub:      'IT Services / Startup',
    location: 'Pakistan',
    year:     '2022',
    url:      'https://techspark.solutions',
    stack:    ['WordPress', 'Beaver Builder', 'PHP', 'CSS3'],
    overview: 'A startup IT services website built to attract B2B clients. Clean layout, strong service hierarchy, team section, and client logos. Beaver Builder used for full flexibility and fast page edits by the client.',
    services: ['Beaver Builder Build', 'B2B Design', 'Service Architecture', 'Client-Editable Pages'],
    img:      'assets/images/services-img.png'
  },
  {
    slug:     'organicbasket',
    title:    'organicbasket.pk',
    category: 'WooCommerce',
    sub:      'Grocery E-Commerce',
    location: 'Pakistan',
    year:     '2022',
    url:      'https://organicbasket.pk',
    stack:    ['WooCommerce', 'WordPress', 'PHP', 'CSS3'],
    overview: 'A grocery delivery e-commerce platform for organic produce in Pakistan. Features include category-based browsing, a quick add-to-cart system, delivery zone selection, and COD + online payment support.',
    services: ['WooCommerce Grocery Store', 'Delivery Zones', 'COD Integration', 'Mobile-First Design'],
    img:      'assets/images/services-img.png'
  }
];
