/* ============================================================
   Services data — shared across services.html & service-detail.html
============================================================ */
var SERVICES = [
  {
    slug:      'wordpress-development',
    icon:      'bi-wordpress',
    num:       '01',
    title:     'WordPress Development',
    tagline:   'Custom WordPress websites built from scratch — fast, flexible, and fully yours.',
    type:      'Web Development',
    timeline:  '2 – 4 Weeks',
    tags:      ['Custom Themes', 'Page Builders', 'Plugin Integration', 'Responsive Design', 'CMS Setup'],
    overview:  'I build WordPress websites tailored to your brand and business goals. Whether you need a simple brochure site or a complex multi-page platform, every project is built with clean code, mobile-first design, and long-term maintainability in mind. No bloated plugins — just lean, purposeful builds that perform.',
    deliverables: ['Custom theme setup', 'Mobile-responsive layout', 'On-page SEO basics', 'Admin training & handoff'],
    process: [
      { step: '01', title: 'Discovery & Planning', desc: 'Understanding your goals, audience, and competitors to define the sitemap and full feature set.' },
      { step: '02', title: 'Design & Wireframe', desc: 'Creating the visual layout and UI flow before a single line of code is written.' },
      { step: '03', title: 'Development', desc: 'Building the site on WordPress with clean, optimised code and your chosen page builder.' },
      { step: '04', title: 'Testing & Launch', desc: 'Cross-browser and device testing, final QA, and a smooth handoff to production.' },
    ],
    faqs: [
      { q: 'Which page builders do you work with?', a: 'I work with Elementor, Divi, Beaver Builder, and Gutenberg (block editor). The choice depends on your budget and how much control you want post-launch.' },
      { q: 'Will I be able to edit the site myself?', a: 'Yes. Every site is set up with a user-friendly CMS so you can update content, images, and pages without touching code.' },
      { q: 'Do you build custom themes from scratch?', a: 'Absolutely. For projects that require full design control or don\'t fit a template, I build bespoke themes from the ground up.' },
      { q: 'How long does a typical WordPress project take?', a: 'Most standard sites take 2–4 weeks from kickoff to launch. Larger or more complex builds may take longer depending on scope.' },
      { q: 'Is hosting and domain included?', a: 'I can set up and configure hosting on your preferred provider, but hosting fees are separate. I recommend reliable managed options like Kinsta or SiteGround.' },
    ],
    relatedSlugs: ['exclusiveprocleaning', 'vortexwise', 'sherdilcloud'],
  },
  {
    slug:      'woocommerce-ecommerce',
    icon:      'bi-bag-check',
    num:       '02',
    title:     'WooCommerce & E-Commerce',
    tagline:   'Online stores that convert — built for growth, speed, and a seamless checkout.',
    type:      'E-Commerce',
    timeline:  '3 – 6 Weeks',
    tags:      ['WooCommerce', 'Payment Gateways', 'Product Pages', 'Cart & Checkout', 'Inventory Setup'],
    overview:  'From single-product shops to large catalogues with hundreds of variants, I build WooCommerce stores that put the customer experience first. Payment gateways, inventory management, shipping rules, and custom checkout flows — all configured and tested so your store is ready to sell from day one.',
    deliverables: ['Full WooCommerce setup', 'Payment gateway integration', 'Product import & config', 'Checkout optimisation'],
    process: [
      { step: '01', title: 'Store Planning', desc: 'Mapping out products, categories, payment options, and shipping rules before development begins.' },
      { step: '02', title: 'Design & UX', desc: 'Designing a conversion-focused store with clear product pages, intuitive navigation, and a smooth cart flow.' },
      { step: '03', title: 'Build & Configure', desc: 'Setting up WooCommerce, payment gateways, tax rules, and all required plugins for a production-ready store.' },
      { step: '04', title: 'Testing & Go-Live', desc: 'Full end-to-end order flow testing, performance checks, and a confident launch.' },
    ],
    faqs: [
      { q: 'Which payment gateways do you support?', a: 'I integrate Stripe, PayPal, Razorpay, and most regional gateways. If you have a specific provider in mind, I can usually accommodate it.' },
      { q: 'Can you migrate my existing store to WooCommerce?', a: 'Yes — I handle migrations from Shopify, Wix, and other platforms, including product data, images, and order history where possible.' },
      { q: 'Do you handle tax and shipping configuration?', a: 'Absolutely. Tax rules, shipping zones, flat-rate and free shipping options, and integration with courier APIs are all part of the build.' },
      { q: 'Can customers get accounts and track orders?', a: 'Yes. WooCommerce includes a full My Account area with order history, address management, and order tracking out of the box.' },
      { q: 'What about store performance and speed?', a: 'Every store is optimised for load speed — compressed images, caching, and lean plugin selection to keep Time to First Byte low.' },
    ],
    relatedSlugs: ['vapehp', 'genzjewellery', 'importedvitamins'],
  },
  {
    slug:      'frontend-development',
    icon:      'bi-code-slash',
    num:       '03',
    title:     'Frontend Development',
    tagline:   'Pixel-perfect, responsive interfaces built with clean HTML, CSS, and JavaScript.',
    type:      'Frontend',
    timeline:  '1 – 3 Weeks',
    tags:      ['HTML / CSS / JS', 'Responsive Design', 'Animations', 'Component Build', 'Bootstrap'],
    overview:  'I build custom frontend interfaces that are fast, accessible, and exactly match the design intent. Using vanilla HTML/CSS/JS or integrating with existing frameworks, every component is crafted with attention to detail — smooth animations, responsive breakpoints, and optimised performance across all devices.',
    deliverables: ['Pixel-perfect HTML/CSS build', 'Fully responsive layout', 'Cross-browser compatible', 'Clean, commented code'],
    process: [
      { step: '01', title: 'Design Review', desc: 'Analysing the design files (Figma, Adobe XD, or screenshots) and defining component structure.' },
      { step: '02', title: 'HTML Structure', desc: 'Building semantic, accessible HTML markup for every section and component.' },
      { step: '03', title: 'Styling & Animation', desc: 'Writing clean, maintainable CSS with smooth transitions, hover states, and responsive breakpoints.' },
      { step: '04', title: 'JS & Interactivity', desc: 'Adding dynamic behaviour — sliders, accordions, modals, and any custom interactions required.' },
    ],
    faqs: [
      { q: 'Can you convert a Figma design to HTML/CSS?', a: 'Yes — I regularly take Figma or Adobe XD files and convert them to clean, production-ready HTML and CSS.' },
      { q: 'Do you use any CSS frameworks?', a: 'I work with Bootstrap and Tailwind, but I\'m equally comfortable writing fully custom CSS without frameworks for leaner output.' },
      { q: 'What about JavaScript frameworks like React or Vue?', a: 'My primary strength is vanilla JS and CSS. For React/Vue-based projects, I can build the component structure and hand off to a framework developer.' },
      { q: 'How do you handle responsive design?', a: 'Mobile-first is my default approach. I design and code from the smallest breakpoint upward, ensuring every layout looks great on all screen sizes.' },
      { q: 'Can you match an existing design or brand style?', a: 'Absolutely. I pay close attention to typography, colour, spacing, and motion to stay true to your design system.' },
    ],
    relatedSlugs: ['techspark', 'thedesignersboutique', 'pixowallpapers'],
  },
  {
    slug:      'website-redesign',
    icon:      'bi-arrow-repeat',
    num:       '04',
    title:     'Website Redesign & Migration',
    tagline:   'Give your existing site a complete refresh without losing what already works.',
    type:      'Redesign / Migration',
    timeline:  '2 – 5 Weeks',
    tags:      ['UI/UX Refresh', 'Platform Migration', 'SEO Preservation', 'Content Migration', 'Speed Audit'],
    overview:  'An outdated website costs you credibility and conversions. I take existing sites — whether on WordPress, Wix, Squarespace, or raw HTML — and redesign them with modern UI, improved UX, and a clean code base. Migrations are handled carefully to preserve SEO rankings, URLs, and content structure.',
    deliverables: ['Full visual redesign', '301 redirects setup', 'Content migration', 'Post-launch monitoring'],
    process: [
      { step: '01', title: 'Site Audit', desc: 'Reviewing the current site for design, performance, SEO, and content issues.' },
      { step: '02', title: 'Redesign Proposal', desc: 'Presenting a new visual direction and sitemap based on the audit findings.' },
      { step: '03', title: 'Build & Migrate', desc: 'Rebuilding the site on the new platform while preserving key URLs and content.' },
      { step: '04', title: 'Launch & Monitor', desc: 'Going live with redirects in place and monitoring for any ranking or traffic changes post-launch.' },
    ],
    faqs: [
      { q: 'Will a redesign affect my Google rankings?', a: 'When done correctly, no. I set up 301 redirects for all changed URLs and preserve your existing SEO structure to protect rankings.' },
      { q: 'Can you migrate from Wix or Squarespace to WordPress?', a: 'Yes. I handle the full migration including content, images, and URL structure, moving your site to a more flexible WordPress setup.' },
      { q: 'What if I want to keep some existing content?', a: 'No problem. I work with your existing copy and media, refreshing the design around it rather than starting from scratch.' },
      { q: 'How do you handle the transition without site downtime?', a: 'The new site is built on a staging environment and tested fully before switching the domain over — minimising downtime to under a minute.' },
      { q: 'Do you also improve site speed during a redesign?', a: 'Always. A redesign is the perfect opportunity to strip out bloat, optimise images, and improve Core Web Vitals.' },
    ],
    relatedSlugs: ['diamond-dpc', 'organicbasket', 'exclusiveprocleaning'],
  },
  {
    slug:      'lms-development',
    icon:      'bi-mortarboard',
    num:       '05',
    title:     'LMS & Online Academy',
    tagline:   'Sell and deliver courses online with a powerful, easy-to-manage learning platform.',
    type:      'LMS / E-Learning',
    timeline:  '3 – 5 Weeks',
    tags:      ['LearnDash', 'LifterLMS', 'Course Builder', 'Student Enrollment', 'Payment Integration'],
    overview:  'I build full learning management systems on WordPress using LearnDash, LifterLMS, or Tutor LMS. From course creation and student enrollment to payment collection and progress tracking — everything is set up and tested so you can focus on teaching, not tech.',
    deliverables: ['Full LMS setup', 'Course & lesson structure', 'Student dashboard', 'Payment & enrollment setup'],
    process: [
      { step: '01', title: 'Platform Selection', desc: 'Recommending the right LMS plugin based on your course structure, budget, and growth plans.' },
      { step: '02', title: 'Site & Course Design', desc: 'Designing the academy site and course pages for a professional, student-friendly experience.' },
      { step: '03', title: 'Setup & Configuration', desc: 'Installing and configuring the LMS, setting up courses, lessons, quizzes, and payment gateways.' },
      { step: '04', title: 'Training & Handoff', desc: 'Walking you through the admin panel so you can add and manage courses independently.' },
    ],
    faqs: [
      { q: 'Which LMS plugins do you work with?', a: 'I primarily work with LearnDash and LifterLMS, but I also have experience with Tutor LMS and MemberPress.' },
      { q: 'Can students get certificates on course completion?', a: 'Yes. Most LMS plugins support auto-generated PDF certificates which can be branded to match your academy.' },
      { q: 'Can I sell courses individually or via subscription?', a: 'Both options are supported. I configure one-time payments, subscription plans, and course bundles depending on your business model.' },
      { q: 'Can I offer free preview lessons?', a: 'Absolutely — free drip lessons, teaser content, and locked-behind-paywall sections are all configurable.' },
      { q: 'Will students be able to track their progress?', a: 'Yes. A full student dashboard shows enrolled courses, completion percentage, quiz scores, and certificates earned.' },
    ],
    relatedSlugs: ['academy-sherdil', 'sherdilcloud'],
  },
  {
    slug:      'seo-performance',
    icon:      'bi-graph-up-arrow',
    num:       '06',
    title:     'SEO & Performance',
    tagline:   'Rank higher, load faster, and convert more — without rebuilding your entire site.',
    type:      'SEO / Optimisation',
    timeline:  '1 – 2 Weeks',
    tags:      ['Technical SEO', 'Core Web Vitals', 'Schema Markup', 'Page Speed', 'Local SEO'],
    overview:  'I audit and optimise existing websites for search engine visibility and loading speed. Using Google Search Console, PageSpeed Insights, and Screaming Frog, I identify the highest-impact issues and fix them — from technical SEO errors and missing schema to image compression and caching configuration.',
    deliverables: ['Full SEO audit report', 'On-page optimisations', 'Schema & meta setup', 'Core Web Vitals improvements'],
    process: [
      { step: '01', title: 'SEO & Speed Audit', desc: 'Running a full crawl and performance analysis to identify all ranking and speed issues.' },
      { step: '02', title: 'Priority Fix Plan', desc: 'Presenting a ranked list of issues by impact, so the most valuable fixes are done first.' },
      { step: '03', title: 'On-Page Optimisation', desc: 'Fixing meta tags, headings, internal links, schema markup, and image alt text across the site.' },
      { step: '04', title: 'Speed Optimisation', desc: 'Implementing caching, image compression, lazy loading, and CDN configuration for faster load times.' },
    ],
    faqs: [
      { q: 'How long before I see results from SEO?', a: 'Technical SEO fixes can show results in 4–8 weeks. Competitive keyword rankings may take 3–6 months depending on your niche and competition.' },
      { q: 'Do you do keyword research?', a: 'Yes — I identify high-intent, achievable keywords for your business and map them to the correct pages on your site.' },
      { q: 'What is a Core Web Vitals score and why does it matter?', a: 'Core Web Vitals are Google\'s page experience metrics (LCP, FID, CLS). Poor scores directly affect your search rankings and user experience.' },
      { q: 'Do you offer ongoing monthly SEO?', a: 'I currently focus on one-off audits and technical fixes. For ongoing monthly SEO management, I can recommend a specialist.' },
      { q: 'Will you fix SEO issues directly or just report them?', a: 'I fix them directly. You receive both a detailed report and a fully optimised site — not just a list of problems to deal with yourself.' },
    ],
    relatedSlugs: ['exclusiveprocleaning', 'vapehp', 'vortexwise'],
  },
];
